name: DiscordBot-Transcoder-CI

on:
  push:
    branches:
      - '**'
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get gcloud CLI utilities
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        project_id: ${{secrets.GCLOUD_PROJECT_ID}}

    - name: Configure Docker for GCP
      run: |
        gcloud auth configure-docker

    - name: Build Container
      run: docker build . -t transcoder

    - name: GCR Push
      run: |
        docker tag transcoder:latest gcr.io/${{secrets.GCLOUD_PROJECT_ID}}/transcoder:latest
        docker push gcr.io/${{secrets.GCLOUD_PROJECT_ID}}/transcoder:latest

    - name: GAE Deploy
      run: |
        gcloud app deploy
